version: 2
jobs:
  build:
    working_directory: ~/project/
    docker:
      - image: circleci/node:12-browsers
    steps:
      - checkout:
          path: ~/project
      - restore_cache:
          key: node-modules-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: node-modules-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: build
          command: ./node_modules/.bin/ng build
      - run:
          name: unit test
          command: ./node_modules/.bin/ng test --watch=false --progress=false --browsers=ChromeHeadlessCI
      - run:
          name: e2e test
          command: ./node_modules/.bin/ng e2e --protractor-config=./e2e/protractor.ci.conf.js
